### ISSUE TITLE
Create Scriptable Objects for Different Tile Types

### ISSUE THREAD

**Issue by ZuhairGhias** [AMastryukov/LD49#3]
https://docs.google.com/document/d/1pBt_uzH_ojEUKuP9OJQYEYceFft3AyUgJrHK-Db-Aek/edit

The document lists various tile types. Find a way to model these in the game. The logic could be attached to tiles, or to a game manager object. TileData is a good name for the Object.

**Comment by AMastryukov** [comment]
The layout of the object should be generally as follows:

```
TilePrefab
- TileScript
  - Pillars
  - TileData (ScriptableObject)
```
